//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.HumanBaxterCollaboration
{
    public class UnityTf : Message
    {
        public const string RosMessageName = "human_baxter_collaboration/UnityTf";

        public Geometry.PoseStamped[] frames;

        public UnityTf()
        {
            this.frames = new Geometry.PoseStamped[0];
        }

        public UnityTf(Geometry.PoseStamped[] frames)
        {
            this.frames = frames;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            
            listOfSerializations.Add(BitConverter.GetBytes(frames.Length));
            foreach(var entry in frames)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            
            var framesArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.frames= new Geometry.PoseStamped[framesArrayLength];
            for(var i = 0; i < framesArrayLength; i++)
            {
                this.frames[i] = new Geometry.PoseStamped();
                offset = this.frames[i].Deserialize(data, offset);
            }

            return offset;
        }

        public override string ToString()
        {
            return "UnityTf: " +
            "\nframes: " + System.String.Join(", ", frames.ToList());
        }
    }
}
